document.write( '<table width="98" height="405" border=2 cellpadding="3" cellspacing="0" background="cirkel.gif">' );
	document.write( '<td>' );
		document.write( '<table height="250" border=0 cellpadding="3" cellspacing="0" bgcolor="" id="huvud">' );
			document.write( '<tr>' );
				document.write( '<td id="huvudm"><a href="index.htm" class="style1">Startsidan</a></td>' );
			document.write( '</tr>' );
			document.write( '<tr>' );
				document.write( '<td id="huvudm"><a href="nyheter.htm" class="style1">Nyheter</a></td>' );
			document.write( '</tr>' );
			document.write( '<tr>' );
				document.write( '<td onMouseOver="visa(hundmeny)" onMouseOut="dolj(hundmeny)" id="huvudm"><div class="style1" >Våra hundar</div></td>' );
			document.write( '</tr>' );
			document.write( '<tr>  ' );
				document.write( '<td id="huvudm"><a href="planerat.htm" class="style1">Planerat</a></td>' );
			document.write( '</tr>' );
			document.write( '<tr>' );
				document.write( '<td onMouseOver="visa(kullmeny)" onMouseOut="dolj(kullmeny)" id="huvudm"><div class="style1" >Valpkullar</div></td>' );
			document.write( '</tr>' );
			document.write( '<tr>' );
				document.write( '<td id="huvudm"><a href="galleri.htm" class="style1">Galleri</a></td>' );
			document.write( '</tr>' );
			document.write( '<tr>' );
				document.write( '<td id="huvudm"><a href="minne.htm" class="style1">Hundar vi minns</a></td>' );
			document.write( '</tr>' );
			document.write( '<tr>' );
				document.write( '<td id="huvudm"><a href="http://www2.olzzon.com/g/g.php?a=s&i=g41-01539-ca" class="style1">Gästbok</a></td>' );
			document.write( '</tr>' );
			document.write( '<tr>' );
				document.write( '<td id="huvudm"><a href="hitta.htm" class="style1">Här bor vi</a></td>' );
			document.write( '</tr>' );
			document.write( '<tr>' );
				document.write( '<td id="huvudm"><a href="lankar.htm" class="style1">Länkar</a></td>' );
			document.write( '</tr>' );
		document.write( '</table>' );

		document.write( '<table onMouseOver="visa(kullmeny)" onMouseOut="dolj(kullmeny)" border id="kullmeny" cellpadding="5" cellspacing="0" style="position: absolute; top: 170px; left: 90px; display: none; border-width: 1pt; border-style: solid; border-color: #F9F9F9" background="#CCCC99">' );
			document.write( '<tr>' );
				document.write( '<td width="125" style="background: #CCCC99" height="20"><div ><a href="sheltiekullar.htm" id="lank" class="style1">Shetland Sheepdog</a></div>' );
				document.write( '</td>' );
			document.write( '</tr>' );
			document.write( '<tr>' );
				document.write( '<td width="125" style="background: #CCCC99" height="20"><div ><a href="bernerkullar.htm" id="lank" class="style1">Berner sennen</a></div>' );
				document.write( '</td>' );
			document.write( '</tr>' );
		document.write( '</table>' );
		document.write( '<table onMouseOver="visa(hundmeny)" onMouseOut="dolj(hundmeny)" border id="hundmeny" cellpadding="5" cellspacing="0" style="position: absolute; top: 120px; left: 100px; display: none; border-width: 1pt; border-style: solid; border-color: #F9F9F9" background="#CCCC99">' );
			document.write( '<tr>' );
				document.write( '<td width="125" style="background: #CCCC99" height="20"><div ><a href="hundar_sheltie.htm" id="lank" class="style1">Shetland Sheepdog</a></div>' );
				document.write( '</td>' );
			document.write( '</tr>' );
			document.write( '<tr>' );
				document.write( '<td width="125" style="background: #CCCC99" height="20"><div ><a href="hundar_berner.htm" id="lank" class="style1">Berner sennen</a></div>' );
				document.write( '</td>' );
			document.write( '</tr>' );
		document.write( '</table>' );
	document.write( '</td>' );
document.write( '</table>');